INSERT INTO maker(id, name) VALUES(1, 'Asus');
INSERT INTO maker(id, name) VALUES(2, 'Lenovo');
INSERT INTO maker(id, name) VALUES(3, 'Hewlett-Packard');
INSERT INTO maker(id, name) VALUES(4, 'Samsung');
INSERT INTO maker(id, name) VALUES(5, 'Seagate');
INSERT INTO maker(id, name) VALUES(6, 'Crucial');
INSERT INTO maker(id, name) VALUES(7, 'Gigabyte');
INSERT INTO maker(id, name) VALUES(8, 'Huawei');
INSERT INTO maker(id, name) VALUES(9, 'Xiaomi');
INSERT INTO maker(id, name) VALUES(10, 'MSI');
INSERT INTO maker(id, name) VALUES(11, 'Intel');
INSERT INTO maker(id, name) VALUES(12, 'AMD');
INSERT INTO maker(id, name) VALUES(13, 'Western Digital');
INSERT INTO maker(id, name) VALUES(14, 'Sony');
INSERT INTO maker(id, name) VALUES(15, 'Apple');
INSERT INTO maker(id, name) VALUES(16, 'Dell');
INSERT INTO maker(id, name) VALUES(17, 'Acer');
INSERT INTO maker(id, name) VALUES(18, 'Toshiba');

INSERT INTO product(id, name, price, id_maker) VALUES(1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO product(id, name, price, id_maker) VALUES(2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO product(id, name, price, id_maker) VALUES(3, 'Disco SSD 1 TB', 150.99, 4);
INSERT INTO product(id, name, price, id_maker) VALUES(4, 'GeForce GTX 1050Ti', 185, 7);
INSERT INTO product(id, name, price, id_maker) VALUES(5, 'GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO product(id, name, price, id_maker) VALUES(6, 'Monitor 24 LED Full HD', 202, 1);
INSERT INTO product(id, name, price, id_maker) VALUES(7, 'Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO product(id, name, price, id_maker) VALUES(8, 'Portátil Yoga 520', 559, 2);
INSERT INTO product(id, name, price, id_maker) VALUES(9, 'Portátil Ideapd 320', 444, 2);
INSERT INTO product(id, name, price, id_maker) VALUES(10, 'Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO product(id, name, price, id_maker) VALUES(11, 'Impresora HP Laserjet Pro M26nw', 180, 3);
INSERT INTO product(id, name, price, id_maker) VALUES(12, 'Tarjeta madre MSI B450', 120, 10);
INSERT INTO product(id, name, price, id_maker) VALUES(13, 'Procesador Intel i7-12700K', 380, 11);
INSERT INTO product(id, name, price, id_maker) VALUES(14, 'Procesador AMD Ryzen 9 5900X', 450, 12);
INSERT INTO product(id, name, price, id_maker) VALUES(15, 'Disco duro externo 2TB', 99.99, 13);
INSERT INTO product(id, name, price, id_maker) VALUES(16, 'Auriculares Sony WH-1000XM4', 299, 14);
INSERT INTO product(id, name, price, id_maker) VALUES(17, 'MacBook Pro 16 M2', 2499, 15);
INSERT INTO product(id, name, price, id_maker) VALUES(18, 'Laptop Dell XPS 13', 1299, 16);
INSERT INTO product(id, name, price, id_maker) VALUES(19, 'Monitor Acer Nitro 27" 165Hz', 350, 17);
INSERT INTO product(id, name, price, id_maker) VALUES(20, 'Laptop Toshiba Satellite', 699, 18);
INSERT INTO product(id, name, price, id_maker) VALUES(21, 'Memoria RAM DDR5 16GB', 180, 6);
INSERT INTO product(id, name, price, id_maker) VALUES(22, 'Disco SSD NVMe 2TB', 220, 13);
INSERT INTO product(id, name, price, id_maker) VALUES(23, 'Router Huawei AX3 WiFi 6', 89.99, 8);
INSERT INTO product(id, name, price, id_maker) VALUES(24, 'Smartphone Xiaomi Redmi Note 11', 199.99, 9);
INSERT INTO product(id, name, price, id_maker) VALUES(25, 'Smartphone Samsung Galaxy S22', 799.99, 4);
INSERT INTO product(id, name, price, id_maker) VALUES(26, 'Memoria USB Kingston 128GB', 35, 6);
INSERT INTO product(id, name, price, id_maker) VALUES(27, 'Teclado mecánico Asus ROG Strix', 150, 1);
INSERT INTO product(id, name, price, id_maker) VALUES(28, 'Mouse Logitech G Pro X', 120, 11);
INSERT INTO product(id, name, price, id_maker) VALUES(29, 'Disco Duro SSD 512GB Samsung EVO', 99.99, 4);
INSERT INTO product(id, name, price, id_maker) VALUES(30, 'Tarjeta gráfica MSI RTX 3060', 450, 10);
INSERT INTO product(id, name, price, id_maker) VALUES(31, 'Tablet Lenovo Tab P11', 329.99, 2);
INSERT INTO product(id, name, price, id_maker) VALUES(32, 'Smartwatch Xiaomi Mi Band 7', 59.99, 9);
INSERT INTO product(id, name, price, id_maker) VALUES(33, 'Laptop Asus ROG Zephyrus', 1899.99, 1);
INSERT INTO product(id, name, price, id_maker) VALUES(34, 'Impresora láser HP OfficeJet Pro', 220, 3);
INSERT INTO product(id, name, price, id_maker) VALUES(35, 'Fuente de poder Gigabyte 750W', 105, 7);
INSERT INTO product(id, name, price, id_maker) VALUES(36, 'Disco Duro Externo Seagate 4TB', 130, 5);
INSERT INTO product(id, name, price, id_maker) VALUES(37, 'AirPods Pro 2', 249.99, 15);
INSERT INTO product(id, name, price, id_maker) VALUES(38, 'Laptop Dell Alienware M15', 2200, 16);
INSERT INTO product(id, name, price, id_maker) VALUES(39, 'Tarjeta gráfica AMD Radeon RX 6800', 620, 12);
INSERT INTO product(id, name, price, id_maker) VALUES(40, 'Monitor Gaming MSI Optix 32"', 499, 10);
INSERT INTO product(id, name, price, id_maker) VALUES(41, 'Cámara Sony Alpha 7 IV', 2500, 14);
INSERT INTO product(id, name, price, id_maker) VALUES(42, 'Cargador portátil Anker 20000mAh', 49.99, 17);
INSERT INTO product(id, name, price, id_maker) VALUES(43, 'Procesador Intel Core i9 13900K', 600, 11);
INSERT INTO product(id, name, price, id_maker) VALUES(44, 'Memoria RAM Corsair 32GB DDR5', 250, 6);
INSERT INTO product(id, name, price, id_maker) VALUES(45, 'Router TP-Link Archer AX50 WiFi 6', 120, 17);
INSERT INTO product(id, name, price, id_maker) VALUES(46, 'Consola PlayStation 5', 499, 14);
INSERT INTO product(id, name, price, id_maker) VALUES(47, 'Xbox Series X', 499, 12);
INSERT INTO product(id, name, price, id_maker) VALUES(48, 'Laptop HP Envy x360', 999, 3);
INSERT INTO product(id, name, price, id_maker) VALUES(49, 'Monitor LG UltraFine 5K', 1300, 14);
INSERT INTO product(id, name, price, id_maker) VALUES(50, 'Mac Mini M2 Pro', 1299, 15);
